on:
  push:
    branches:
      - 'main'
      - 'feature/github_actions'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build proj
        run: |
          sudo apt-get update && sudo apt-get install -y libgtest-dev
          cmake ./01 -DPATCH_VERSION=${{ github.run_number }}
          cmake --build ./01
          cmake --build ./01 --target test_version
          cmake --build ./01 --target package
      - name: Create Release_01
        id: create_release
        uses: actions/create-release@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release_01  ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release_01 Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./01/helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

